import { readFileSync, writeFileSync } from 'node:fs'

// globals.css is the palette source for both utility classes and native styles.
const css = readFileSync('globals.css', 'utf8')
const palettes = Object.fromEntries(
  ['light', 'dark'].map((mode) => {
    const block = css.match(new RegExp(`@variant ${mode} \\{([^}]+)}`))?.[1] ?? ''
    return [
      mode,
      Object.fromEntries(
        [...block.matchAll(/--color-([\w-]+):\s*([^;]+);/g)].map(([, key, value]) => [
          key.replace(/-([a-z])/g, (_, c) => c.toUpperCase()),
          value.trim(),
        ]),
      ),
    ]
  }),
)
const output = `// Generated by bun run theme:generate. Edit globals.css.\nexport const colors = ${JSON.stringify(palettes, null, 2)} as const\nexport type Colors = { [K in keyof typeof colors.light]: string }\n`
if (process.argv.includes('--check')) {
  if (readFileSync('src/theme/colors.ts', 'utf8') !== output)
    throw new Error('Run bun run theme:generate')
} else writeFileSync('src/theme/colors.ts', output)
